[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"
litvm_testnet = "https://liteforge.rpc.caldera.xyz/http"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
